apply plugin: 'com.android.application'

android {
    compileSdk 34

    compileOptions {
        sourceCompatibility 11
        targetCompatibility 11
    }

    defaultConfig {
        applicationId "moe.dic1911.urlsanitizer"
        minSdkVersion 23
        //noinspection ExpiredTargetSdkVersion
        targetSdkVersion 30
        versionCode 32
        versionName "3.0.2"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    namespace 'moe.dic1911.urlsanitizer'
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.0'
    implementation 'androidx.navigation:navigation-fragment:2.8.5'
    implementation 'androidx.navigation:navigation-ui:2.8.5'

}
